addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.12.1")
addSbtPlugin("io.gatling"     % "gatling-sbt"     % "4.19.2")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.6.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"   % "2.4.4")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.2.1")
